webapp/ethereum_analysis/ethereum_analysis/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('app/', include('ethereum_analysis_app.urls')),
    path('admin/', admin.site.urls),
]

webapp/ethereum_analysis/ethereum_analysis_app/urls.py
from django.urls import path, re_path

from . import views

app_name = 'ethereum_analysis_app'

urlpatterns = [
    path('', views.index, name='index'),
    re_path(r'^exchange_rates$', views.exchange_rates_for_country, name='exchange_rates_for_country')
]

webapp/ethereum_analysis/ethereum_analysis_app/models.py
# This is an auto-generated Django model module.
# You'll have to do the following manually to clean this up:
#   * Rearrange models' order
#   * Make sure each model has one field with primary_key=True
#   * Make sure each ForeignKey and OneToOneField has `on_delete` set to the desired behavior
#   * Remove `managed = False` lines if you wish to allow Django to create, modify, and delete the table
# Feel free to rename the models, but don't rename db_table values or field names.
from django.db import models


class AddressDimension(models.Model):
    address_id = models.BigAutoField(primary_key=True)
    address = models.CharField(max_length=100)
    balance = models.FloatField(blank=True, null=True)

    class Meta:
        db_table = 'address_dimension'


class CountryDimension(models.Model):
    idcountry_dimension = models.BigAutoField(primary_key=True)
    name = models.CharField(max_length=45)
    code = models.CharField(max_length=5)
    region = models.CharField(max_length=45)
    currency = models.CharField(max_length=45)
    currency_code = models.CharField(max_length=5, blank=True, null=True)

    class Meta:
        db_table = 'country_dimension'


class DaiTransactions(models.Model):
    dai_transactions_id = models.BigAutoField(primary_key=True)
    hash = models.CharField(unique=True, max_length=255)
    block_number = models.BigIntegerField()
    to_address = models.ForeignKey(AddressDimension, models.DO_NOTHING,related_name='to_address')
    from_address = models.ForeignKey(AddressDimension, models.DO_NOTHING,related_name='from_address')
    value = models.FloatField()
    gas = models.BigIntegerField()
    gas_price = models.BigIntegerField()
    transaction_fee = models.BigIntegerField()
    input = models.TextField()
    block_timestamp = models.BigIntegerField()
    date = models.ForeignKey('DateDimension', models.DO_NOTHING)
    date_0 = models.DateField(db_column='date')  # Field renamed because of name conflict.

    class Meta:
        db_table = 'dai_transactions'


class DateDimension(models.Model):
    date_id = models.BigAutoField(primary_key=True)
    date = models.DateField()
    day = models.BigIntegerField()
    month = models.BigIntegerField()
    year = models.BigIntegerField()

    class Meta:
        db_table = 'date_dimension'


class UsdExchangeRates(models.Model):
    usdexchangerates_id = models.BigAutoField(primary_key=True)
    country = models.ForeignKey(CountryDimension, models.DO_NOTHING)
    value = models.FloatField()
    date = models.ForeignKey(DateDimension, models.DO_NOTHING)
    date_0 = models.DateField(db_column='date')  # Field renamed because of name conflict.

    class Meta:
        db_table = 'usd_exchange_rates'

webapp/ethereum_analysis/ethereum_analysis_app/views.py
from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse, JsonResponse
from django_pandas.io import read_frame
from .models import *
from django.db import connection
from django.db.models import Q
from bokeh.plotting import figure, output_file, show
from bokeh.models import ColumnDataSource,CustomJS,HoverTool
from bokeh.embed import components
from bokeh.models.formatters import DatetimeTickFormatter
from bokeh.palettes import Viridis
import os
import datetime
import time
import random
import pdb
import pandas as pd

def retrieve_eth_usd_in(range_of_timestamps):
    source = pd.read_json("ETL/data_source/exchange_rates/eth_to_usd.json")
    exchanges = source['Data']['Data']
    data_frame_data = {'date':[], 'value':[]}
    for elem in exchanges:
        if(elem['time'] in range_of_timestamps):
            data_frame_data['date'].append(datetime.datetime.fromtimestamp(elem['time']))
            data_frame_data['value'].append(elem['close'])
        elif(elem['time'] > range_of_timestamps[len(range_of_timestamps) - 1]):
            break

    return pd.DataFrame(data_frame_data).set_index('date')

def calculate_txs_amount_in_usd(df_txs, df_exchanges):
    #convert wei value to ether (1 wei = 1000000000000000000 ether)
    df_txs['value_in_ether'] = [(value * 1000000000000000000) for value in df_txs['amount']]
    #df_txs[to_usd] = df_exchanges[df_exchanges.date == txs.date]['value'] * txs['value_in_ether'] for txs in df_t
    usd_values = []
    for txs in df_txs.itertuples():
        usd_values.append(df_exchanges[df_exchanges.index.date == txs[0]]['value'] * txs[3])
    df_txs['value_to_usd'] = [elem[0] for elem in usd_values]


def DAI_txs_group_by_date():
    dai_transactions = DaiTransactions.objects.all()
    dai_transactions_df = read_frame(dai_transactions).set_index('dai_transactions_id')
    group_by_dates = dai_transactions_df.groupby('date_0')
    txs_per_day = group_by_dates.size().to_frame()
    txs_per_day = txs_per_day.rename(columns={0:'count'})
    txs_per_day["amount"] = group_by_dates.sum()['value']
    #retrieve exchanges ETH/USD
    eth_to_usd = retrieve_eth_usd_in(list(time.mktime(txs_date.timetuple()) for txs_date in txs_per_day.index))
    calculate_txs_amount_in_usd(txs_per_day, eth_to_usd)
    return txs_per_day

def index(request):

    countries_with_exchanges = UsdExchangeRates.objects.order_by('country').distinct('country').values('country')
    countries_with_exchanges = CountryDimension.objects.filter(idcountry_dimension__in=countries_with_exchanges)
    countries_with_exchanges_df = read_frame(countries_with_exchanges)
    group_by_region = countries_with_exchanges_df.groupby('region')
    #for country in countries_with_exchanges:
    #    countries_ids_with_exchanges.append(country.)
    #query = 'select * from country_dimension where idcountry_dimension in %s'
    #countries_with_exchanges = CountryDimension.objects.raw(query, params=[tuple(countries_ids_with_exchanges)])

    #retrieve dai txs
    txs_per_day = DAI_txs_group_by_date()
    source = ColumnDataSource.from_df(txs_per_day)

    plot = figure(title="DAI's transactions", y_axis_label= "Transaction's count", plot_width=1000, plot_height=500)
    l=plot.line(x='date_0',y='count', legend= "DAI's transactions", line_width=2, source=source)
    plot.xaxis.formatter = DatetimeTickFormatter(days=["%d %m %Y"])

    # adding hover interaction to plot
    hover = HoverTool(tooltips=[('date',"@date_0{%Y-%m-%d}"),('count','@count'),('amount','@amount{(0,0.0)}'),('amount in usd','@value_to_usd{($ 0.00 a)}')],formatters={'date_0':'datetime'})
    plot.add_tools(hover)

    script, div = components(plot)
    return render(request,'ethereum_analysis_app/index.html',{'script': script, 'div': div, 'countries_by_region': group_by_region})


def exchange_rates_for_country(request):
    # start and end dates for not retrieve all exchanges rates
    start_date = datetime.date(2019,11,23)
    end_date = datetime.date(2019,12,13)

    # retrieve dai's txs again to calculate amount in country currency
    txs_per_day = DAI_txs_group_by_date()

    country_selected = request.GET.get("country_select")
    country_selected = CountryDimension.objects.filter(name=country_selected).first()
    exchange_rates = UsdExchangeRates.objects.filter(Q(country=country_selected) & Q(date_0__range=(start_date,end_date)))
    exchange_rates_df = read_frame(exchange_rates).set_index('usdexchangerates_id')
    exchange_rates_df['txs_amount_in_country_currency'] = 0

    for ec in exchange_rates_df.itertuples():
        txs_amount_in_usd = txs_per_day[txs_per_day.index==ec[4]]['value_to_usd']
        print("txs value in USD = " + str(txs_amount_in_usd))
        print("country currency/USD = "+ str(ec[2]))
        print("product="+str(txs_amount_in_usd * ec[2]))
        #pdb.set_trace()
        exchange_rates_df.loc[ec[0],'txs_amount_in_country_currency'] = ec[2] * txs_amount_in_usd.values[0] if txs_amount_in_usd.size > 0 else 0

    source = ColumnDataSource.from_df(exchange_rates_df)

    title = "USD/" + country_selected.currency_code + " Exchange rates"
    exchange_rates_plot = figure(title=title, y_axis_label=country_selected.currency, plot_width=1000, plot_height=500)
    exchange_rates_plot.line(x='date_0', y='value', legend=country_selected.currency, line_width=2, line_color=random.choice(random.choice(Viridis)), source=source)
    exchange_rates_plot.xaxis.formatter = DatetimeTickFormatter(days=["%d %m %Y"])

    # adding hover interaction to plot
    hover = HoverTool(tooltips=[('date',"@date_0{%Y-%m-%d}"),('value','@value'),("DAI's txs in " + country_selected.currency_code,'@txs_amount_in_country_currency{($ 0.00 a)}')],formatters={'date_0':'datetime'})
    exchange_rates_plot.add_tools(hover)

    er_script, er_div = components(exchange_rates_plot)
    return JsonResponse({'er_script': er_script, 'er_div': er_div})

webapp/ethereum_analysis/ethereum_analysis_app/templates/ethereum_analysis_app/index.html
<!DOCTYPE html>
<html>

  <head>
      <meta charset="utf-8">
      <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
      <meta name="description" content="">
      <meta name="author" content="">

      <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
      {% load static %}
      <script type="text/javascript" src="{% static 'app.js' %}"></script>

      <! bokeh -->
      <link href= "https://cdn.bokeh.org/bokeh/release/bokeh-1.4.0.min.css" rel="stylesheet" type="text/css">
      <link href="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-1.4.0.min.css" rel="stylesheet" type="text/css">
      <script src="https://cdn.bokeh.org/bokeh/release/bokeh-1.4.0.min.js"></script>
      <script src="https://cdn.bokeh.org/bokeh/release/bokeh-widgets-1.4.0.min.js"></script>
      <script src="https://cdn.bokeh.org/bokeh/release/bokeh-tables-1.4.0.min.js"></script>

      {{ script | safe }}

      <title>DAI's analysis </title>

    	{# Cargamos la librería #}
  	  {% load bootstrap4 %}

  	  {# CSS Bootstrap #}
  	  {% bootstrap_css %}

      <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
      </style>

    </head>

    <body>

        <nav class="navbar navbar-dark bg-dark flex-md-nowrap p-0 shadow">
          <a class="navbar-brand col-sm-5 col-md-3 mr-0" href="#">DAI's transactions analytics</a>
        <!--  <ul class="navbar-nav px-3">
            <li class="nav-item text-nowrap">
              <a class="nav-link" href="#">Sign out</a>
            </li>
          </ul> -->
        </nav>

        <div class="container-fluid">
          <div class="row">
            <nav class="col-md-2 d-none d-md-block bg-light sidebar">
              <div class="sidebar-sticky">
                <form class="form" id="exchange_rate_form" name="exchange_rate_form" method="GET" action="{% url 'ethereum_analysis_app:exchange_rates_for_country' %}">
                  {% csrf_token %}
                  <div class="form-group">
                    <label class="my-1 mr-2" for="country_select">Country/Currency</label>
                    <select class="custom-select my-1 mr-sm-2" name="country_select" id="country_select">
                        {% for region,countries in countries_by_region %}
                          <optgroup label="{{ region }}">
                            {% for country in countries.itertuples %}
                              <option value={{country.name}}>{{ country.name }}({{country.code}})/{{country.currency}}({{country.currency_code}})</option>
                            {% endfor %}
                          </optgroup>
                        {% endfor %}
                    </select>
                    <small id="passwordHelpInline" class="text-muted">You can select exchange rates to USD to view DAI's transfers amount in real currency</small>
                  </div>
                  <button type="submit" class="btn btn-primary btn-block">Show</button>
                </form>
<!--                <h6 class="sidebar-heading d-flex justify-content-between align-items-center px-3 mt-4 mb-1 text-muted">
                  <span>Saved reports</span>
                  <a class="d-flex align-items-center text-muted" href="#" aria-label="Add a new report">
                    <span data-feather="plus-circle"></span>
                  </a>
                </h6>
                <ul class="nav flex-column mb-2">
                  <li class="nav-item">
                    <a class="nav-link" href="#">
                      <span data-feather="file-text"></span>
                      Current month
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">
                      <span data-feather="file-text"></span>
                      Last quarter
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">
                      <span data-feather="file-text"></span>
                      Social engagement
                    </a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="#">
                      <span data-feather="file-text"></span>
                      Year-end sale
                    </a>
                  </li>
                </ul>-->
              </div>
            </nav>

          <main role="main" class="col-md-9 ml-sm-auto col-lg-10 px-4">
              <div class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom">
                <h1 class="h2">Dashboard</h1>
                <div class="btn-toolbar mb-2 mb-md-0">
                  <div class="btn-group mr-2">
<!--                    <button type="button" class="btn btn-sm btn-outline-secondary">Share</button>
                    <button type="button" class="btn btn-sm btn-outline-secondary">Export</button>-->
                  </div>
<!--                  <button type="button" class="btn btn-sm btn-outline-secondary dropdown-toggle">
                    <span data-feather="calendar"></span>
                    This week
                  </button> -->
                </div>
              </div>

              {{ div | safe }}
              <div id="exchange_rates_plot">

              </div>

          </main>
        </div>
      </div>
    <script>window.jQuery || document.write('<script src="/docs/4.4/assets/js/vendor/jquery.slim.min.js"><\/script>')</script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/feather-icons/4.9.0/feather.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js"></script>
    {# JS y jQuery Bootstrap #}
    {% bootstrap_javascript jquery='full' %}
    </body>

</html>

webapp/ethereum_analysis/ethereum_analysis_app/templates/ethereum_analysis_app/update_index.html
{{ er_script | safe }}
{{ er_div | safe }}